### ISSUE TITLE
Inline named type

### ISSUE THREAD

**Issue by Virgiel** [cornucopia-rs/cornucopia#103]
By default, we use the name of the function as a base for the name of generated types. This is a good default but it can generate long and weird names. At the same time, using two lines to declare named params and row is cumbersome if they are only used once.

I propose the following:
```sql
--! insert_everything_array EveryArrParams(): EveryArr(date?)
INSERT INTO EverythingArray (...) VALUES (...);
```
Having the same meaning as this:
```sql
--: EveryArrParams
--: EveryArr(date?)
--! insert_everything_array EveryArrParams: EveryArr
INSERT INTO EverythingArray (...) VALUES (...);
```

At the exception that those named type cannot be reused in other queries.

**Comment by Virgiel** [comment]
We might make the `()` mandatory again for named type declaration to prevent confusion between declaration and use.

```sql
--: EveryArrParams()
--: EveryArr(date?)
--! insert_everything_array EveryArrParams: EveryArr
INSERT INTO EverythingArray (...) VALUES (...);
```

**Comment by LouisGariepy** [comment]
> By default, we use the name of the function as a base for the name of generated types. This is a good default but it can generate long and weird names. At the same time, using two lines to declare named params and row is cumbersome if they are only used once.
> 
> I propose the following:
> 
> ```sql
> --! insert_everything_array EveryArrParams(): EveryArr(date?)
> INSERT INTO EverythingArray (...) VALUES (...);
> ```
> 
> Having the same meaning as this:
> 
> ```sql
> --: EveryArrParams
> --: EveryArr(date?)
> --! insert_everything_array EveryArrParams: EveryArr
> INSERT INTO EverythingArray (...) VALUES (...);
> ```
> 
> At the exception that those named type cannot be reused in other queries.

Ok, I like this!
