### ISSUE TITLE
Improve notes when cornucopia fails to start a container

### ISSUE THREAD

**Issue by aclueless** [cornucopia-rs/cornucopia#111]
Hi,
I tried to use cornucopia yesterday. It failed to start a container and showed some notes that I think it can be improve:

* Don't show note about docker if user provide the '-p' flag.
* A container can also fail if the postgres port is already in use. I think it's useful to remind user that this may be the cause.

**Comment by LouisGariepy** [comment]
Thanks for the feedback! Will fix. 

In general, the error messages for the upcoming version are vastly improved :smile: . I'll make sure to also include this particular diagnostic.

**Comment by LouisGariepy** [comment]
While we're at it, cornucopia's ephemeral managed container should probably use an obscure port number instead of postgres' default to avoid collisions like this.
