### ISSUE TITLE
Clarify named type

### ISSUE THREAD

**Issue by Virgiel** [cornucopia-rs/cornucopia#119]
With the support of inlined named type and previous syntax improvements, named types are becoming confusing by my fault. `Type` sometimes means a declaration `--: Type`, sometimes means a binding to a previously declared named type `--! query Row`, or it can also mean an implicit declaration of a named type. `--! query Row` and `--! query Row()` work the same, until reused in another query and then, in the first case, both queries use the same named type and in the other case, the second query declares implicitly a new type that is not compatible with the first. I see two ways to make things clearer.

## Strict syntax

Declaration requires `()` and you must declare a named type before using it, such as:
```sql
--: Row

--! query Params: Row
SQL

--! select Params: AnotherRow
SQL
```
becomes
```sql
--: Row()
--: Params()

--! query Params: Row
SQL

--! select Params: AnotherRow()
SQL
```

## Relaxed syntax

Declared and inlined named type become the same, the first one being recommanded but not mandatory when use in several places such as:
```sql
--: Row

--! query Params(): Row
SQL

--! select Params: AnotherRow
SQL
```
is the same as
```sql
--: Row()
--: Params()
--: AnotherRow()

--! query Params: Row
SQL

--! select Params: AnotherRow
SQL
```

Strict syntax is more verbose but easier to understand. In contrast, relaxed syntax is less verbose and more permissive but still coherent.

**Comment by LouisGariepy** [comment]
The strict syntax is clearer and compact enough IMO. I think we should go with it unless you have a case for the relaxed syntax.
