### ISSUE TITLE
Use schema file instead of migrations files

### ISSUE THREAD

**Issue by Virgiel** [cornucopia-rs/cornucopia#128]
I do not use migrations files in my projects and by the way, I am not sure cornucopia should handle migrations. I would like to be able to pass a schema file to the CLI instead of migrations.

```
cornucopia generate --schema schema.sql
```

**Comment by LouisGariepy** [comment]
> I am not sure cornucopia should handle migrations.

Yeah you're probably right. Its a lot of effort to make a fully-fledged migration tool right and there are many tools that already handle this workflow.

This is a pretty easy change internally (although breaking from an API point of view). I think we should get this in for 0.8?

**Comment by Virgiel** [comment]
I am in favour of removing the whole migration logic. We could always recommend a good migration library in our documentation.
We could accept a list of schema paths, when the paths are directories we run all the SQL files in them in their logical order and when it's a SQL file we run it in arg order. This way, you can just give a schema file, schema files in a directory or filtered migration files (with grep for example to use only the 'up' files)
