### ISSUE TITLE
User Experience: Panics forces user to manually close container instance

### ISSUE THREAD

**Issue by WIGGLES-dev** [cornucopia-rs/cornucopia#146]
When running cornucopia codegen panics caused by parsing the query or schema files result in the backing container being left running. This forces the user to go into docker cli or docker desktop and manually delete the container.

FIX: Either reuse existing containers (probably easier) or close the open daemon when a call to codegen panics.

**Comment by LouisGariepy** [comment]
Thanks for reporting :smile: 

Cornucopia tries its best to cleanup before returning an error. If there's a bug in there, I really want to fix it!

1. Are you using the lib or the CLI?
2. I'd be very thankful if you could provide an example error message?

**Comment by LouisGariepy** [comment]
For reference, here's the code responsible to cleanup on errors: https://github.com/cornucopia-rs/cornucopia/blob/7b67f9e218040a78dacf41948111a45e46ba7fe9/cornucopia/src/cli.rs#L68-L80.

If you are using the lib, you can replicate the same behavior as in the above link yourself (the needed items are public).

**Comment by LouisGariepy** [comment]
@WIGGLES-dev Are you still having trouble with this issue?

**Comment by WIGGLES-dev** [comment]
Manually cleaning up worked for me.
