### ISSUE TITLE
Rename `params` to `param_struct`

### ISSUE THREAD

**Issue by LouisGariepy** [cornucopia-rs/cornucopia#155]
I think it makes the concept more explicit. We could also rename the trait `Params` to `ParamStruct`

**Comment by LouisGariepy** [comment]
@Virgiel Looking at https://github.com/cornucopia-rs/cornucopia/issues/154#issuecomment-1251623171 it seems you  favor renaming `bind` to `args` and `params` to `struct`, is that right?

**Comment by Virgiel** [comment]
I develop the name change proposal further in #154.

**Comment by LouisGariepy** [comment]
Closing in favor of #154. This present issue's scope is narrower, so I doesn't really make sense to discuss it separately from the broader changes proposed in #154.
