### ISSUE TITLE
Update MSRV

### ISSUE THREAD

**Issue by LouisGariepy** [cornucopia-rs/cornucopia#170]
According to cargo-msrv, our MSRV is 1.62.1. Right now we advertise a MSRV of 1.56, so we should update that.

I'll delay this issue until we're ready to release in case the MSRV changes again.

**Comment by dyaramatreya** [comment]
Hi @LouisGariepy,
Can I take up this issue for a good first issue/contribution?

**Comment by LouisGariepy** [comment]
Sure! This should be pretty straightforward, the only file to change is this one: https://github.com/cornucopia-rs/cornucopia/blob/main/README.md.

**Comment by LouisGariepy** [comment]
Closed by #175
