### ISSUE TITLE
Work with both sync and async

### ISSUE THREAD

**Issue by Virgiel** [cornucopia-rs/cornucopia#176]
Currently, we generate either async or sync code. This is problematic if someone wants to use both in their project because types are declared twice and
therefore are incompatible.

I propose a new codegen module architecture to support both in a single file:

``` rs
pub mod types {
    // Common database declared types (Enum & composite)
    pub mod public { /* ... */ }
}
pub mod queries {
    // For each query file
    pub mod copy {
        // Common queries types (Row, Params & Borrowed)
        pub mod types { /* ... */}
        // Generated type for synchronous usage (Stmt & Query)
        pub mod sync { /* ... */ }
        // Generated type for asynchronous usage (Stmt & Query)
        pub mod tokio { /* ... */ }
    }
}
```

**Comment by dbofmmbt** [comment]
I think you can work around it by generating code twice for two different destinations, e.g. 
- `src/cornucopia_sync.rs`
- `src/cornucopia_async.rs`

Actually, I think this may be a good solution for this use case. What do you think?

**Comment by Virgiel** [comment]
The problem with this solution is that the database and row types are generated in both `src/cornucopia_sync.rs` and
`src/cornucopia_async.rs`. Even though they have the same name and fields, from the point of view of the Rust type system they come from different modules and are therefore incompatible, which I would like to fix

**Comment by LouisGariepy** [comment]
@Virgiel I could see it being useful for perfomance reason to *choose either* sync or async for specific queries (using an *async* keyword in our annotations, for example), but I'm not sure I understand what kind of project would need to have both at the same time for all queries.

I'm not opposed, but I'd like to understand the motivation behind it.

**Comment by jacobsvante** [comment]
Could be a CLI in an app that doesn't require async (and would be more cleanly written without). Then the main part of the app requires async (e.g. web server).

**Comment by LouisGariepy** [comment]
@jacobsvante That would be more akin to what I suggested, wouldn't it (have some queries be sync and some be async)?

I still don't see why you would need both sync and async versions of *all* queries for that usecase.

**Comment by jacobsvante** [comment]
Thanks for your thorough reply, @LouisGariepy.

I personally don't have a use case for sharing queries/types etc currently, but I can see how the synchronous CLI might want to use the same query as the async web server app (e.g. fetch all products matching the given criteria).

**Comment by Virgiel** [comment]
I have a web backend where I have asynchronous endpoints and synchronous workers. I prefer to use synchronous code where I can as it is way easier to use correctly when thing get complicated. 

I use some queries only in sync, some only in async and other in both. We could declare synchronicity per query or per module, but generating async and sync variant for every query is the simplest solution that work for all cases, without changing our current syntax.

I am currently revising my proposal to make it simpler and compatible with current code.

When we generate only sync or only async :
```rs
pub mod types {
    // Common database declared types (Enum & composite)
}
pub mod queries {
    pub mod module {
        // Common queries types (Row, Params & Borrowed)
        // Generated type for synchronous or asynchronous usage (Stmt & Query)
    }
}
```

When we generate both:
```rs
pub mod types {
    // Common database declared types (Enum & composite)
}
pub mod queries {
    pub mod module {
        // Common queries types (Row, Params & Borrowed)
        // Generated type for synchronous usage (Stmt & Query)
        pub mod sync { /* ... */ }
        // Generated type for asynchronous usage (Stmt & Query)
        pub mod tokio { /* ... */ }
    }
}
```

**Comment by LouisGariepy** [comment]
If there are only a few of such queries, then it should be fairly straightforward to implement `From` conversions, which would likely get optimized away.

But, if you use this pattern very extensively, or if your queries involve a lot of different types, I can see how this becomes unwieldy.

Now that I understand the reasoning (worker threads + web server), I can support the proposal. We should be very careful to make the implementation neat and tidy though, to not bloat the existing code.

I think your amendment made this a non-breaking change? So I'll remove that tag. And I'm confident we can work the PR into a merge-able state.

See you in the PR :smile:.
