### ISSUE TITLE
Very small issue in doc

### ISSUE THREAD

**Issue by massimo79m** [cornucopia-rs/cornucopia#222]
In "Query annotation" section

--! **_authors_from_country_**
SELECT id, name, age 
FROM Authors 
WHERE Authors.nationality = :country;

The --! token indicates a Cornucopia query annotation, and **_select_authors_** is the name of the query.

"authors_from_country" should be fixed with "select authors" in the query annotation.

**Comment by Arthurdw** [comment]
~ This should be closed

**Comment by Arthurdw** [comment]
@massimo79m this issue has been resolved. _(see ref above this)_
