### ISSUE TITLE
deadpool-postgres 0.11

### ISSUE THREAD

**Issue by VPaulV** [cornucopia-rs/cornucopia#224]
Hi guys, 

.bind() is not working with deadpool-postgres 0.11. Is it possible to add support for the latest deadpool-postgres?
0.10 works fine, but 0.11 fails with:
```
error: the trait bound `deadpool::managed::Object<Manager>: cornucopia_async::GenericClient` is not satisfied
label: required by a bound introduced by this call
```
```
error: the trait bound `deadpool::managed::Object<Manager>: cornucopia_async::GenericClient` is not satisfied
label: the trait `cornucopia_async::GenericClient` is not implemented for `deadpool::managed::Object<Manager>`
note: required by a bound in `InsertUserStmt::bind`
label: the trait `cornucopia_async::GenericClient` is not implemented for `deadpool::managed::Object<Manager>`
the trait bound `deadpool::managed::Object<Manager>: cornucopia_async::GenericClient` is not satisfied
the following other types implement trait `cornucopia_async::GenericClient`:
  deadpool_postgres::Transaction<'_>
  Client
  ```

**Comment by jacobsvante** [comment]
Having the same issue. Using the git repo instead of cornucopia-async v0.4.0 seems to work. @LouisGariepy @Virgiel time for a new release?

**Comment by LouisGariepy** [comment]
I released two new versions of `cornucopia_async`. We should find a sustainable way to manage user-facing dependencies, but it should fix the issue for now, until there's a new version of `deadpool-postgres` :-).

**Comment by jacobsvante** [comment]
`cornucopia_async@v0.6.0` works great with `deadpool-postgres@0.12.1`! Thank you @LouisGariepy! :D

**Comment by jacobsvante** [comment]
@LouisGariepy This seems to be back with deadpool-postgres@0.13... Can you make a 0.7 release for new deadpool version?
