### ISSUE TITLE
Expose a library equivalent to the CLI.

### ISSUE THREAD

**Issue by LouisGariepy** [cornucopia-rs/cornucopia#55]
Suggested in this discussion https://github.com/LouisGariepy/cornucopia/discussions/53.

This would allow Cornucopia to be used more ergonomically in automated environments, build scripts, and even other rust crates.

**Comment by Virgiel** [comment]
The problem is that we need a working Postgres database. I found [pg-embed](https://github.com/faokunega/pg-embed), but I don't like the idea of downloading and running a binary from an untrusted source.

**Comment by LouisGariepy** [comment]
My intention with this issue was to allow users to do something like :
```rust
let cornucopia = cornucopia::Cornucopia;
let generated_code = cornucopia
    .url("some/cool/url")
    //.podman() <-- or this
    //.docker() <-- or that
    .query_dir("...")
    .generate();
```
That would work without an embedded DB. I probably misunderstood what feature you really wanted though (sorry :smile:), so please let me know!

**Comment by Virgiel** [comment]
This would be useful, especially when using build scripts! I was also thinking of a built-in option, but it's hard to do this properly with Postgres and can be done later.
