### ISSUE TITLE
Null everywhere 

### ISSUE THREAD

**Issue by Virgiel** [cornucopia-rs/cornucopia#65]
Currently, we can declare the nullity of the returned rows fields:

```sql
CREATE TYPE composite AS (
    name TEXT,
    age INT NOT NULL
);

CREATE TABLE items (
    composite composite,
    name TEXT NOT NULL,
    data BYTEA,
    datas BYTEA[]
);
```

```sql
--! items ?{composite, data, datas}
SELECT * FROM items;
```

This is enough to cover the nullity of `data`, `datas` and `composite` but not the values of `datas` and `composite.name`.

## Nullable array value

We need a way to declare the nullity of the array and the values of the array independently which current syntax does not allow.

We could get back to something close to the old syntax:
- `datas?` means nullable array
- `datas[?]` means nullable array values
- `datas?, datas[?]` or `datas?[?]` means nullable array and array values
```sql
--! items {composite?, data?, datas?[?]}
SELECT * FROM items;
```

# Nullable composite fields

We could declare it in functions declaration:

- `composite?` means nullable composite
- `composite.name?` means nullable composite's name
- `composite?, composite.name?` or `composite?.name?` means nullable composite and composite's name 

```sql
--! items {composite?.name?, data?, datas?}
SELECT * FROM items;
```

But this implies a redeclaration each time we use this composite type. We could add a new syntax to declare the nullity of fields of database types :

```sql
--:db composite{name?}
```

# Nullable parameters

We could use the same syntax for parameters and rows:

```sql
--! new_items (composite?, data?, datas?[?]) {data?}
INSERT INTO items (composite, name, data, datas) 
  VALUES (:composite, :name, :data, :datas) 
  RETURNING name, data;
```

# Nullable named generated types fields

Depends on #63 

We could also use this syntax for named generated type :
```sql
--:params ItemParams{composite?, data?, datas?[?]}
--:row Item{composite?, data?, datas?[?]}

--! new_items (IdParams) -> Item
INSERT INTO items (composite, name, data, datas) 
  VALUES (:composite, :name, :data, :datas) 
  RETURNING *;
```

**Comment by Virgiel** [comment]
Can I start working on it?

**Comment by Virgiel** [comment]
I am already working on #63. However, I am not very familiar with `pest`'s grammar, so I would appreciate your help with this!

**Comment by LouisGariepy** [comment]
I'll update and provide a copy here as soon as possible.

**Comment by LouisGariepy** [comment]
There's still the open question of nesting : do we handle things like `array_col[.some_composite_col?]` or `a.b?.c.d?`. This seems pretty hard implementation-wise.

I also think it could be useful to have a wildcard when you need nullable everywhere, but it also opens a whole can of worms (is the nullability applied recursively, etc...).

I'm pretty sure adding either or both of these in the future would require a significant rewrite of the work introduced in this PR, so I think we should decide now if we want to support them or not.

**Comment by Virgiel** [comment]
I managed to support nullable array values in codegen without too much complexity, for the nullability of composite fields types we should use the declarative approach for now:

```sql

--:db composite(name?)
```

If one day we support multi-dimensional arrays (which even `postgres` does not natively support) we could think of a more complex nullability declaration for array and composite type.

**Comment by Virgiel** [comment]
If people have a compelling use where some fields of a composite type are only nullable for certain queries and they can't bear the cost of some unwraps in their code to handle this, we might consider that but I doubt it is worth the cost

**Comment by LouisGariepy** [comment]
> If people have a compelling use where some fields of a composite type are only nullable for certain queries and they can't bear the cost of some unwraps in their code to handle this, we might consider that but I doubt it is worth the cost

Sounds reasonable to me!

**Comment by Virgiel** [comment]
What remains to be done is support for internal nullity for array values and database types (supported by the parser and codegen but not yet linked).

For arrays, I proposed the following syntax:
```sql
--:row Item(datas?[?])
```

For simplicity, we should not accept separate declarations like:
```sql
--:row Item(datas?, datas[?])
```

**Comment by LouisGariepy** [comment]
I'm in favor!
