### ISSUE TITLE
Enable CI caching

### ISSUE THREAD

**Issue by LouisGariepy** [cornucopia-rs/cornucopia#75]
Maybe this? https://github.com/Swatinem/rust-cache. Or this? https://github.com/actions/cache/blob/main/examples.md#rust---cargo

**Comment by Virgiel** [comment]
I also think that the `Check` action is redundant with the `Test Suite` action as the tests should not compile without the whole code passing the checks.

**Comment by LouisGariepy** [comment]
Looks good to me, CI went from ~4m to ~1m15s.
