### ISSUE TITLE
Benchmarks.

### ISSUE THREAD

**Issue by LouisGariepy** [cornucopia-rs/cornucopia#97]
I think this could be a useful tool to detect regressions, and evaluate the benefits of performance-related improvements. My main goal is to compare with `postgres`/`tokio_postgres`, since we aim to be a thin wrapper on top of these, and not a comparison with all the other DB crates out there.

We could take some inspiration on the diesel benchmarks https://github.com/diesel-rs/diesel/tree/master/diesel_bench.

**Comment by weiznich** [comment]
It would be great to have this as entry to the diesel benchmark suite as well. Can you submit a PR for that?

**Comment by LouisGariepy** [comment]
Hey @weiznich, big fan of your work :smiley: 

Thanks for the invitation, I think it'd be great to integrate with Diesel's benchmarks. I don't know when I'll get time to submit a PR, but I'll keep a note on my roadmap!
